## Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
# For Open-PS2-Loader
## Thanks to:
# - izdubar@psx-scene and jimmikaelkael@psx-scene
#   <http://psx-scene.com/forums/f150/%5Blinux%5D-opl-compile-guides-63749/>
# - Bat Rastard@psx-scene and doctorxyz@psx-scene
#   <http://psx-scene.com/forums/f150/2015-linux-mint-vm-creation-opl-compiling-guide-ps2sdk-127047/index3.html#post1169435>
# - and a lot of people around internet :)

dist: trusty
sudo: required
language: c
cache: ccache

## Fix make_changelog.sh
git:
  depth: 9999999

before_install:
  ## Save env dir
  - cd ../
  - export TRAVIS_ENV_DIR=$(pwd)

install:
  ## Dependencies
  - sudo apt-get install -yqqq patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev ccache

before_script:
  ## Make cleanup, just for prevent anything
  - rm -rf ${TRAVIS_ENV_DIR}/ps2toolchain/
  - rm -rf ${TRAVIS_ENV_DIR}/ps2sdk-ports/
  - rm -rf ${TRAVIS_ENV_DIR}/ps2-packer/
  - rm -rf ${TRAVIS_ENV_DIR}/gsKit/

  ## Set up the environment
  - export PS2DEV=${TRAVIS_ENV_DIR}/ps2dev
  - export PS2SDK=${PS2DEV}/ps2sdk
  - export PATH=${PATH}:${PS2DEV}/bin:${PS2DEV}/ee/bin:${PS2DEV}/iop/bin:${PS2DEV}/dvp/bin:${PS2SDK}/bin
  - export GSKIT=${PS2DEV}/gsKit
  - export LANG=C
  - export LC_ALL=C

  ## Clone all
  - cd ${TRAVIS_ENV_DIR}
  - git clone --depth=1 https://github.com/ps2dev/ps2toolchain.git
  - git clone --depth=1 https://github.com/ps2dev/ps2sdk-ports.git
  - git clone --depth=1 https://github.com/ps2dev/ps2-packer.git
  - git clone --depth=1 https://github.com/ps2dev/gsKit.git

  ## ps2dev/ps2toolchain
  - cd ${TRAVIS_ENV_DIR}/ps2toolchain/
  - bash ./toolchain.sh > /tmp/OPNPS2LD-PS2TOOLCHAIN.log 2>&1

  ## ps2dev/ps2sdk-ports/zlib
  - cd ${TRAVIS_ENV_DIR}/ps2sdk-ports/zlib/
  - make
  - make install

  ## ps2dev/ps2sdk-ports/libpng
  - cd ${TRAVIS_ENV_DIR}/ps2sdk-ports/libpng/
  - make
  - make install

  ## ps2dev/ps2sdk-ports/libjpeg
  - cd ${TRAVIS_ENV_DIR}/ps2sdk-ports/libjpeg/
  - make
  - make install

  ## ps2dev/ps2sdk-ports/freetype
  - cd ${TRAVIS_ENV_DIR}/ps2sdk-ports/freetype-2.4.12/
  - bash ./SetupPS2.sh

  ## ps2dev/ps2-packer
  - cd ${TRAVIS_ENV_DIR}/ps2-packer/
  - make
  - make install

  ## ps2dev/gsKit
  - cd ${TRAVIS_ENV_DIR}/gsKit/
  - make
  - make install

script:
  ## Go back to opl dir
  - cd ${TRAVIS_BUILD_DIR}/

  ## Let's build Open PS2 Loader Release!
  - make release

  ## Make the lang pack
  - bash ./lng_pack.sh

before_deploy:
  - export OPL_VERSION=$(make oplversion)
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis-CI"
  - git tag ${OPL_VERSION}

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  skip_cleanup: true
  target_commitish: ${TRAVIS_COMMIT}
  name: OPL v${OPL_VERSION}
  body: Automated release from Travis CI
  file:
    - ${TRAVIS_BUILD_DIR}/OPNPS2LD-${OPL_VERSION}.ZIP
    - ${TRAVIS_BUILD_DIR}/OPNPS2LD_LANGS-${OPL_VERSION}.zip
  on:
    branch: master
