## Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
# For Open-PS2-Loader
## Thanks to:
# - izdubar@psx-scene and jimmikaelkael@psx-scene
#   <http://psx-scene.com/forums/f150/%5Blinux%5D-opl-compile-guides-63749/>
# - Bat Rastard@psx-scene and doctorxyz@psx-scene
#   <http://psx-scene.com/forums/f150/2015-linux-mint-vm-creation-opl-compiling-guide-ps2sdk-127047/index3.html#post1169435>
# - and a lot of people around internet :)

dist: trusty
sudo: required
language: c
cache: ccache

## Fix make_changelog.sh
git:
  depth: 9999999

before_install:
  ## Save env dir
  - cd ../
  - export TRAVIS_ENV_DIR=$(pwd)

install:
  ## Dependencies
  - sudo apt-get install -yqqq make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev ccache cmake

before_script:
  ## Make cleanup, just for prevent anything
  - rm -rf ${TRAVIS_ENV_DIR}/repo
  - rm -rf ${TRAVIS_ENV_DIR}/ps2dev
  - rm -rf ${TRAVIS_ENV_DIR}/ps2dev-repo

  ## Set up the environment
  - export PS2DEV=${TRAVIS_ENV_DIR}/ps2dev
  - export PS2SDK=${PS2DEV}/ps2sdk
  - export PATH=${PATH}:${TRAVIS_ENV_DIR}/repo:${PS2DEV}/bin:${PS2DEV}/ee/bin:${PS2DEV}/iop/bin:${PS2DEV}/dvp/bin:${PS2SDK}/bin
  - export GSKIT=${PS2DEV}/gsKit
  - export LANG=C
  - export LC_ALL=C

  ## Get repo
  - cd ${TRAVIS_ENV_DIR}
  - mkdir repo
  - curl https://storage.googleapis.com/git-repo-downloads/repo > repo/repo
  - chmod a+x repo/repo

  ## Clone all
  - cd ${TRAVIS_ENV_DIR}
  - mkdir ps2dev-repo
  - cd ps2dev-repo
  - repo init -u https://github.com/rickgaiser/ps2dev-repo -b master --depth=1
  - repo sync -j4 -c --no-tags

  ## ps2dev/ps2toolchain
  - ./build-binutils-ee.sh > /tmp/build-binutils-ee.log 2>&1
  - ./build-binutils-iop.sh > /tmp/build-binutils-iop.log 2>&1
  - ./build-gcc-ee-stage1.sh > /tmp/build-gcc-ee-stage1.log 2>&1
  - ./build-gcc-iop-stage1.sh > /tmp/build-gcc-iop-stage1.log 2>&1
  - ./build-newlib.sh > /tmp/build-newlib.log 2>&1
  - ./build-gcc-ee-stage2.sh > /tmp/build-gcc-ee-stage2.log 2>&1
  - ./build-ps2sdk.sh > /tmp/build-ps2sdk.log 2>&1
  - ./build-tools.sh > /tmp/build-tools.log 2>&1
  - ./build-libs.sh > /tmp/build-libs.log 2>&1

script:
  ## Go back to opl dir
  - cd ${TRAVIS_BUILD_DIR}/

  ## Let's build Open PS2 Loader Release!
  - make release

  ## Make the lang pack
  - bash ./lng_pack.sh

before_deploy:
  - export OPL_VERSION=$(make oplversion)
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis-CI"
  - git tag ${OPL_VERSION}

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  skip_cleanup: true
  target_commitish: ${TRAVIS_COMMIT}
  name: OPL v${OPL_VERSION}
  body: Automated release from Travis CI
  file:
    - ${TRAVIS_BUILD_DIR}/OPNPS2LD-${OPL_VERSION}.zip
    - ${TRAVIS_BUILD_DIR}/OPNPS2LD_LANGS-${OPL_VERSION}.zip
  on:
    branch: master
